plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.3'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.ytlearner'
version = '1.0.0'
//sourceCompatibility = '17'

repositories {
    mavenCentral()
}

//java {
//    toolchain {
//        languageVersion = JavaLanguageVersion.of(17)
//    }
//}

dependencies {
    // Spring Boot starters
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // Runtime DB for development
    runtimeOnly 'com.h2database:h2'

    // PostgreSQL for production
    runtimeOnly 'org.postgresql:postgresql:42.7.7'

    // Lombok - compileOnly so it's not packaged
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.3'

    // Google Auth
    implementation 'com.google.api-client:google-api-client:2.9.0'
//    implementation 'com.google.oauth-client:google-oauth-client-jetty:1.35.2'

    implementation 'com.google.oauth-client:google-oauth-client:1.39.0'

    implementation 'com.fasterxml.jackson.core:jackson-core:2.21.2'

    // OkHttp for external HTTP calls
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'

    // Jackson
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // Validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Tests
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

//tasks.withType(JavaCompile).configureEach {
//    options.encoding = 'UTF-8'
//}

// Keep lombok out of the final executable jar by using compileOnly above.
